# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/node:dubnium-stretch

  working_directory: ~/tmp/circlci-now

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp/circlci-now
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-cache-{{ .Branch }}
            # fallback to using the latest cache if no exact match is found
            - npm-cache-
      - run:
          name: 'Install dependencies'
          command: |
            npm install
            npm run bootstrap
      - run:
          name: 'Build projects'
          command: |
            npm run build
      - run:
          name: Install Code Climate test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  set-up:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/circlci-now
      - run:
          name: 'Set up NPM'
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: 'Set up Git'
          command: |
            git config user.email "cedric@niriu.com"
            git config user.name "drixsonic"

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/circlci-now
      - run:
          name: 'Lint'
          command: |
            npm run lint

  unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/circlci-now
      - run:
          name: 'Unit tests'
          command: |
            ./tmp/cc-test-reporter before-build
            npm test
            for f in packages/*; do
              if [ -d "$f" ]; then
                echo $f
                if [ -d "$f/coverage" ]; then
                  ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/coverage.${f//\//-}.json $f/coverage/lcov.info
                fi
              fi
            done;
            ./tmp/cc-test-reporter sum-coverage -o tmp/coverage.total.json tmp/coverage.*.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/coverage.total.json -r $CC_TEST_REPORTER_ID

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tmp/circlci-now
      - add_ssh_keys:
          fingerprints:
            - '16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48'
      - run:
          name: 'Publish to NPM'
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              npm run release
            fi

workflows:
  version: 2
  tests:
    jobs:
      - checkout
      - set-up:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - unit-tests:
          requires:
            - checkout
      - publish:
          requires:
            - set-up
            - lint
            - unit-tests
